### ISSUE TITLE
cannot install through python setup.py install

### ISSUE THREAD

**Issue by annathoma** [libindic/indic-trans#25]
![er](https://user-images.githubusercontent.com/22562366/37479129-e97b3c82-28a1-11e8-9fa4-f71c71b35309.png)

what to do to install them.
Please help

**Comment by priyanka22kar** [comment]
yes I have got the same error please help

**Comment by priyanka22kar** [comment]
![image](https://user-images.githubusercontent.com/26005427/43071011-0ccb2b54-8e8f-11e8-8f23-3311578ddfa6.png)
Please help 
not able to clone the directory 
thank you

**Comment by irshadbhat** [comment]
Sorry for posting the solution so late. But here is the solution:

1. open `setup.cfg` file and delete line 4 and 5 (description-file =  README.rst)
2. run python `setup.py clean`
3. run python `setup.py install`

Apparently the issue is with `pbr`. `pbr` is parsing the `README.rst` in `cp1252 encoding`. This encoding can't translate Indic scripts in `README`, thus raising the decode error.
