### ISSUE TITLE
Support for Bhojpuri, Rajasthani

### ISSUE THREAD

**Issue by loretoparisi** [libindic/indic-trans#28]
Thanks for this amazing work!
I'm not sure (sorry if I'm confusing some languages) if the transliteration tool is missing the models for Bhojpuri, Rajasthani languages.
To clarify, I have composed this table for the current models support:

Lang | ISO 639-3 | ISO 639-2 | TRANS MODEL | NOTES
-- | -- | -- | -- | --
Hindi | hin | hi | YES
Tamil | tam | ta | YES
Telugu | tel | te | YES
Punjabi | pan | pa | YES | Panjabi
Marathi | mrt | mr | YES
Gujarati | guj | gu | YES
Bengali | ben | be | YES
Kannada | kan | kn | YES
Bhojpuri | bho | bh | **NO** | Bihari languages: Bhojpuri, Magahi, and Maithili
Malayalam | mal | ml | YES
Urdu | urd | ur | YES
Rajasthani | raj | - | **NO**
Odia (Oriya) | ori | or | YES
Assamese | asm | as | YES
Nepali | nep | ne | YES
Bodo | brx |   | YES
Konkani | kok | - | YES

Is that correct?

**Comment by irshadbhat** [comment]
The transliteration work done here is a supervised task modelled as a sequence-to-sequence tagging problem using structured perceptron. Currently we don't support Bhojpuri and Rajasthani because there is no parallel corpus available for these languages. These languages are very resource poor. There isn't even a good amount of monolingual data available for these languages.

**Comment by loretoparisi** [comment]
@irshadbhat thanks a lot for the clarification, looking forward for it.
